version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    steps:
      - checkout
      - run: docker compose up
      - run: wait-for-it.sh localhost:8080 -- echo "docker image is running fine"
      - run: docker compose down

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
