  version: 2.1
  jobs:
    run-test:
      # Steps to the job
      steps:
        - checkout
        - run: docker pull nginxdemos/hello
        - run:
            name: Open docker container
            command: docker compose up
        - run: wait-for-it.sh localhost:8080 -- echo "docker image is running fine"
        - run:
            name: Close docker container
            command: docker compose down

  # Invoke jobs via workflows
  workflows:
    run-test-workflow:
      jobs:
        - run-test






